auctions/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listing/<int:id>", views.listing, name="listing")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"

class Auction(models.Model):
    name = models.CharField(max_length=64)
    price = models.FloatField()
    CATEGORIES = ((1, "Fashion"), (2, "Toys"), (3, "Electronics"), (4, "Home"), (5, "Others"))
    category = models.IntegerField(choices=CATEGORIES, default=5)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="auctions/",null=True)
    description = models.TextField(max_length=1000, blank=True)

    def __str__(self):
        return f"{self.name} starts at {self.price}"

class Bid(models.Model):
    price = models.FloatField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bid")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="bids")
    
    def __str__(self):
        return f"{self.user} bids {self.price} for {self.auction}"

class Comment(models.Model):
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comments")
    
    def __str__(self):
        return f"{self.user} commented: {self.comment} about {self.auction}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django import forms

from .models import User, Auction


def index(request):
    return render(request, "auctions/index.html", {
        "auctions": Auction.objects.all()
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

categories = (
    (1, "Fashion"),
    (2, "Toys"),
    (3, "Electronics"),
    (4, "Home"),
    (5, "Others")
)

class CreateListingForm(forms.Form):
    name = forms.CharField()
    description = forms.CharField(
        widget=forms.Textarea()
    )
    starting_bid = forms.FloatField()
    image = forms.URLField(required=False)
    category = forms.TypedChoiceField(choices = categories,
                                    coerce = str 
                                    )

@login_required
def create(request):
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            new_listing = Auction()
            new_listing.name = form.cleaned_data['name']
            new_listing.description = form.cleaned_data['description']
            new_listing.price = form.cleaned_data['starting_bid']
            new_listing.image = form.cleaned_data['image']
            new_listing.category = form.cleaned_data['category']
            new_listing.save()
            return render(request, "auctions/listing.html", {
                "listing": new_listing
            })
    return render(request, "auctions/create.html", {
        "form": CreateListingForm()
    })

def listing(request, id):
    listing = Auction.objects.get(id=id)
    print(listing.name)
    return render(request, "auctions/listing.html", {
        "listing": listing
    })

auctions/templates/auctions/create.html
{% extends 'auctions/layout.html' %}
{% load widget_tweaks %}
{% block body %}
<form action="{% url 'auctions:create' %}" method="POST">
    {% csrf_token %}

    {% for hidden_field in forms.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control col-md-5" %}
    </div>
    {% endfor %}
    {% if error %}
        <div class="alert alert-warning col-md-5">{{ error }}</div>
    {% endif %}
    <input type="submit" class="btn btn-primary" value="Create">
</form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load i18n %}

{% block body %}
    <h2>Active Listings</h2>
    {% for auction in auctions %}
        <div class="card p-2 mx-auto text-center">
            <img class="card-img img-thumbnail rounded mx-auto" style="height:25%; width:25%" src="{{ auction.image.url }}">
            <div class="card-body">
                <a href="{% url 'auctions:listing' auction.id %}"><h5 class="card-title font-weight-bold">{{auction.name}}</h5></a>
                <h6 class="card-subtitle mb-2">Price: ${{auction.price}}</h6>
                <h7 class="card-subtitle mb-2 text-muted">Created: {{ auction.created }}</h7>
            </div>
        </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}
{% load static %}

{% block title %}
{{ listing.name }}
{% endblock %}

{% block body %}
<div class="container-fluid">
    <h3 class="font-weight-bold">Listing: {{ listing.name }}</h3>
    <img class="col-md-3 p-2" src="{{ listing.image.url }}">
    {% if not listing.description %}
        <p class="text-muted p-2">no description.</p>
    {% else %}
        <p class="text-muted p-2">{{ listing.description }}</p>
    {% endif %}
    <h4 class="col-md-3 p-2 font-weight-bold">${{ listing.price }}<h4>
    <form class="form-inline col-md-3 p-2">
        <div class="form-group pr-2">
            <small class="form-text text-muted"></small>
            <input type="text" class="form-control" placeholder="your bid">
        </div>
        <button type="submit" class="btn btn-primary">Place Bid</button>
    </form>
    <div>
        <h4 class="col-md-3 p-2 font-weight-bold">Details:</h4>
        <ul>
            <li></li>
            <li></li>
        </ul>
    </div>
</div>

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}